require 'json'

class SeedProducts < ActiveRecord::Migration
  def change
    json_array = data

    json_array.each_with_index do |json_product, index|
      break if index >= 100

      p = Product.new
      p.name = json_product["name"]
      p.short_desc = json_product["shortDescription"]
      p.best_selling_rank = json_product["bestSellingRank"]
      p.thumbnail = json_product["thumbnailImage"]
      p.price = json_product["salePrice"]
      p.manufacturer = json_product["manufacturer"]
      p.url = json_product["url"]
      p.product_type = json_product["type"]
      p.image = json_product["image"]
      p.category = json_product["category"]
      p.free_shipping = !json_product["shipping"].nil?
      p.save
  end

  def data
    JSON.parse( <<-json
      [
        {
          "name": "Webroot SecureAnywhere Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
          "shortDescription": "Safeguard your PC, Mac, Android and iOS devices with comprehensive Internet protection",
          "bestSellingRank": 4,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1688/1688832_54x108_s.gif",
          "salePrice": 49.99,
          "manufacturer": "Webroot",
          "url": "http://www.bestbuy.com/site/webroot-secureanywhere-internet-security-3-device-1-year-subscription-mac-windows/1688832.p?id=1219060687969&skuId=1688832&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Software",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1688/1688832_105x210_sc.jpg",
          "customerReviewCount": 5980,
          "category": "Computer Security Software",
          "objectID": 1688832,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Geek Squad® - Tech Support Membership (1 Year)",
          "shortDescription": "Who has time for frustrating computer issues? With unlimited coverage for all your computing issues, Geek Squad Tech Support is the expert resource you need to keep your PC, Mac or tablet (up to three devices) up and running, no matter where you bought them. Get convenient help any way you'd like: in store, online or on the phone.",
          "bestSellingRank": 7,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1853/1853259_s.gif",
          "salePrice": 199.99,
          "manufacturer": "Geek Squad®",
          "url": "http://www.bestbuy.com/site/geek-squad-tech-support-membership-1-year/1853259.p?id=1218323911480&skuId=1853259&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1853/1853259_sc.jpg",
          "customerReviewCount": 3306,
          "category": "Virus & Spyware Removal",
          "objectID": 1853259,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "Apple® - 3.3' Lightning-to-USB 2.0 Cable",
          "shortDescription": "Compatible with most Apple&#174; iPad&#174;, iPhone&#174; and iPod&#174; models with a Lightning connector; charges and syncs your device; reversible design",
          "bestSellingRank": 12,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6652/6652043_s.gif",
          "salePrice": 19.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-3-3-lightning-to-usb-2-0-cable/6652043.p?id=1218803451837&skuId=6652043&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6652/6652043_sc.jpg",
          "customerReviewCount": 569,
          "category": "Data Cables",
          "objectID": 6652043,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Google - Chromecast HDMI Streaming Media Player",
          "shortDescription": "Casts online video and music to your HDTV from popular apps like Netflix, YouTube, HBO GO, Hulu Plus, Pandora, Crackle, ESPN, MLB.TV, Google Play Movies & TV, Google Play Music, Chrome* and more; plug in and play; works across platforms; no remote required",
          "bestSellingRank": 17,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9071/9071056_s.gif",
          "salePrice": 35.0,
          "manufacturer": "Google",
          "url": "http://www.bestbuy.com/site/google-chromecast-hdmi-streaming-media-player/9071056.p?id=1219013308425&skuId=9071056&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9071/9071056_sc.jpg",
          "customerReviewCount": 5872,
          "category": "Streaming Media Players",
          "objectID": 9071056,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Kaspersky Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
          "shortDescription": "Provide comprehensive protection to up to three devices in your home",
          "bestSellingRank": 24,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1689/1689012_s.gif",
          "salePrice": 49.99,
          "manufacturer": "Kaspersky Lab",
          "url": "http://www.bestbuy.com/site/kaspersky-internet-security-3-device-1-year-subscription-mac-windows/1689012.p?id=1219060668483&skuId=1689012&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Software",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1689/1689012_sc.jpg",
          "customerReviewCount": 1252,
          "category": "Kaspersky Lab",
          "objectID": 1689012,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Logitech - Marathon Mouse M705 Wireless Laser Mouse - Black",
          "shortDescription": "Laser technology; Unifying receiver; wireless USB interface",
          "bestSellingRank": 25,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1325/1325119_s.gif",
          "salePrice": 39.99,
          "manufacturer": "Logitech",
          "url": "http://www.bestbuy.com/site/logitech-marathon-mouse-m705-wireless-laser-mouse-black/1325119.p?id=1218250610754&skuId=1325119&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1325/1325119_sc.jpg",
          "customerReviewCount": 9,
          "category": "Wireless Mice",
          "objectID": 1325119,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Toshiba - Satellite 15.6\" Laptop - Intel Celeron - 4GB Memory - 500GB Hard Drive - Jet Black",
          "shortDescription": "Windows 8.1 64-bitTechnical details: Intel&#174; Celeron&#174; processor; 15.6\" display; 4GB memory; 500GB hard driveSpecial features: HDMI outputNote: DVD/CD drive not included",
          "bestSellingRank": 28,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6841/6841014_s.gif",
          "salePrice": 228.99,
          "manufacturer": "Toshiba",
          "url": "http://www.bestbuy.com/site/toshiba-satellite-15-6-laptop-intel-celeron-4gb-memory-500gb-hard-drive-jet-black/6841014.p?id=1219241419174&skuId=6841014&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6841/6841014_sc.jpg",
          "customerReviewCount": 14,
          "category": "PC Laptops",
          "objectID": 6841014,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "SanDisk - Cruzer 16GB USB 2.0 Flash Drive - Black",
          "shortDescription": "For PC, Mac and Linux; retractable USB connector; drag-and-drop file backup; includes SanDisk SecureAccess software; access to 2GB of YuuWaa Cloud storage",
          "bestSellingRank": 29,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226875_s.gif",
          "salePrice": 7.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-cruzer-16gb-usb-2-0-flash-drive-black/9226875.p?id=1218062423830&skuId=9226875&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226875_sc.jpg",
          "customerReviewCount": 871,
          "category": "USB Flash Drives",
          "objectID": 9226875,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra Plus 16GB SDHC Class 10 UHS-1 Memory Card",
          "shortDescription": "Compatible with most devices with a SDHC card slot; 16GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
          "bestSellingRank": 34,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142535_s.gif",
          "salePrice": 14.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-plus-16gb-sdhc-class-10-uhs-1-memory-card/3142535.p?id=1219088212869&skuId=3142535&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142535_sc.jpg",
          "customerReviewCount": 273,
          "category": "Secure Digital",
          "objectID": 3142535,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Office Home & Student 2013 - Windows",
          "shortDescription": "Create, communicate and learn using streamlined touch, pen or keyboard commands",
          "bestSellingRank": 39,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/7016/7016127_54x54_s.gif",
          "salePrice": 139.99,
          "manufacturer": "Microsoft",
          "url": "http://www.bestbuy.com/site/office-home-student-2013-windows/7016127.p?id=1218821792097&skuId=7016127&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Software",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/7016/7016127_105x105_sc.jpg",
          "customerReviewCount": 3510,
          "category": "Office Software Suites",
          "objectID": 7016127,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "Apple® - TV",
          "shortDescription": "3rd generation; compatible with most HDTVs with an HDMI interface; allows you to stream movies, TV shows, photos and music from your computer to your HDTV or home theater system; 802.11a/b/g/n wireless LAN. \nLearn more about smart products.",
          "bestSellingRank": 46,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/4854/4854433_s.gif",
          "salePrice": 89.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-tv/4854433.p?id=1218552476525&skuId=4854433&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/4854/4854433_sc.jpg",
          "customerReviewCount": 7280,
          "category": "Streaming Media Players",
          "objectID": 4854433,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Monthly Accidental Protection Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 48,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif",
          "salePrice": 9.99,
          "url": "http://www.bestbuy.com/site/monthly-accidental-protection-plan-geek-squad/1752369.p?id=1219064726785&skuId=1752369&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
          "customerReviewCount": null,
          "category": null,
          "objectID": 1752369,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Insignia™ - 4' Lightning Charge-and-Sync Cable",
          "shortDescription": "Compatible with select Apple&#174; iPad&#174;, iPhone&#174; and iPod&#174; models; lets you charge and sync Apple devices; 4' length",
          "bestSellingRank": 49,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019369_s.gif",
          "salePrice": 14.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-4-lightning-charge-and-sync-cable/5019369.p?id=1219106282393&skuId=5019369&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019369_sc.jpg",
          "customerReviewCount": null,
          "category": "Data Cables",
          "objectID": 5019369,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Apple® - EarPods™ with Remote and Mic - White",
          "shortDescription": "In-line remote and mic; compatible with select Apple iPhone, iPod and iPad models; sweat- and water-resistant design",
          "bestSellingRank": 52,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6848/6848136_s.gif",
          "salePrice": 29.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-earpods-with-remote-and-mic-white/6848136.p?id=1218809156050&skuId=6848136&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6848/6848136_sc.jpg",
          "customerReviewCount": 2524,
          "category": "Headphones",
          "objectID": 6848136,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "HP - 564XL Ink Cartridge - Black",
          "shortDescription": "Compatible with select HP Photosmart printers; black ink; 1 cartridge",
          "bestSellingRank": 53,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1982/1982034_s.gif",
          "salePrice": 23.99,
          "manufacturer": "HP",
          "url": "http://www.bestbuy.com/site/hp-564xl-ink-cartridge-black/1982034.p?id=1218304547043&skuId=1982034&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1982/1982034_sc.jpg",
          "customerReviewCount": 1550,
          "category": "Printer Ink",
          "objectID": 1982034,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra Plus 32GB SDHC Class 10 UHS-1 Memory Card",
          "shortDescription": "Compatible with most devices with a SDHC card slot; 32GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
          "bestSellingRank": 58,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142553_s.gif",
          "salePrice": 24.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-plus-32gb-sdhc-class-10-uhs-1-memory-card/3142553.p?id=1219088217648&skuId=3142553&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142553_sc.jpg",
          "customerReviewCount": 192,
          "category": "Secure Digital",
          "objectID": 3142553,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Cruzer 32GB USB 2.0 Flash Drive - Black",
          "shortDescription": "High-speed USB 2.0 interface for fast data transfer; U3 enabled; PC and Mac compatible",
          "bestSellingRank": 60,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9288/9288807_s.gif",
          "salePrice": 14.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-cruzer-32gb-usb-2-0-flash-drive-black/9288807.p?id=1218075402509&skuId=9288807&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9288/9288807_sc.jpg",
          "customerReviewCount": 619,
          "category": "USB Flash Drives",
          "objectID": 9288807,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra Plus 32GB microSDHC Class 10 UHS-1 Memory Card",
          "shortDescription": "Compatible with most devices with a microSDHC card slot; 32GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
          "bestSellingRank": 63,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142635_s.gif",
          "salePrice": 24.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-plus-32gb-microsdhc-class-10-uhs-1-memory-card/3142635.p?id=1219088213853&skuId=3142635&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142635_sc.jpg",
          "customerReviewCount": 193,
          "category": "Micro SD Memory",
          "objectID": 3142635,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "The Raid 2 (2 Disc) (Unrated) (Ultraviolet Digital Copy) (Blu-ray Disc)",
          "shortDescription": null,
          "bestSellingRank": 64,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6938/6938047s.jpg",
          "salePrice": 19.99,
          "url": "http://www.bestbuy.com/site/the-raid-2-2-disc-unrated-ultraviolet-digital-copy-blu-ray-disc/6938047.p?id=3231559&skuId=6938047&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Movie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6938/6938047.jpg",
          "customerReviewCount": 1,
          "category": "Movies & TV Shows",
          "objectID": 6938047,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Dynex™ - 6' HDMI Cable",
          "shortDescription": "Connects an HDMI source to an HDTV or projector with an HDMI input; supports HDMI Ethernet Channel (HEC) and Audio Return Channel (ARC); compatible with most screen refresh rates",
          "bestSellingRank": 65,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/2648/2648583_s.gif",
          "salePrice": 19.99,
          "manufacturer": "Dynex™",
          "url": "http://www.bestbuy.com/site/dynex-6-hdmi-cable/2648583.p?id=1218342637879&skuId=2648583&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/2648/2648583_sc.jpg",
          "customerReviewCount": 2511,
          "category": "HDMI Cables",
          "objectID": 2648583,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "LG - 8x External Double-Layer DVD±RW/CD-RW Drive",
          "shortDescription": "USB 2.0 interface; slim, portable design; up to 6x DVD+R DL and DVD-R DL, 8x DVD+R and DVD-R write speeds; up to 6x DVD+RW and DVD-RW rewrite speeds; 24x24x24 CD-RW",
          "bestSellingRank": 66,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1802/1802006_s.gif",
          "salePrice": 39.99,
          "manufacturer": "LG",
          "url": "http://www.bestbuy.com/site/lg-8x-external-double-layer-dvdrw-cd-rw-drive/1802006.p?id=1219064878253&skuId=1802006&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1802/1802006_sc.jpg",
          "customerReviewCount": 726,
          "category": "External DVD Drives",
          "objectID": 1802006,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Insignia™ - 6' HDMI Cable - Black",
          "shortDescription": "Connects 1 HDMI component to another HDMI component via HDMI connection; supports 1080p high-definition resolution; up to 10.2 Gbps bandwidth; 6' length",
          "bestSellingRank": 71,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/4127/4127007_s.gif",
          "salePrice": 19.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-6-hdmi-cable-black/4127007.p?id=1219096725673&skuId=4127007&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/4127/4127007_sc.jpg",
          "customerReviewCount": 24,
          "category": "HDMI Cables",
          "objectID": 4127007,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Dynex™ - 3.9' HDMI Cable - Black",
          "shortDescription": "Connects 2 HDMI components; supports HEC (HDMI Ethernet Channel) and ARC (Audio Return Channel)",
          "bestSellingRank": 72,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5681/5681548_s.gif",
          "salePrice": 9.99,
          "manufacturer": "Dynex™",
          "url": "http://www.bestbuy.com/site/dynex-3-9-hdmi-cable-black/5681548.p?id=1218679202438&skuId=5681548&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5681/5681548_sc.jpg",
          "customerReviewCount": 1571,
          "category": "HDMI Cables",
          "objectID": 5681548,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra Plus 16GB microSDHC Class 10 UHS-1 Memory Card",
          "shortDescription": "Compatible with most devices with a microSDHC card slot; 16GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
          "bestSellingRank": 73,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142599_s.gif",
          "salePrice": 14.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-plus-16gb-microsdhc-class-10-uhs-1-memory-card/3142599.p?id=1219088213592&skuId=3142599&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142599_sc.jpg",
          "customerReviewCount": 140,
          "category": "Micro SD Memory",
          "objectID": 3142599,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Cruzer 8GB USB 2.0 Flash Drive - Black",
          "shortDescription": "For PC, Mac and Linux; retractable USB connector; drag-and-drop file backup; includes SanDisk SecureAccess software; access to 2GB of YuuWaa Cloud storage",
          "bestSellingRank": 75,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226777_s.gif",
          "salePrice": 5.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-cruzer-8gb-usb-2-0-flash-drive-black/9226777.p?id=1218062421405&skuId=9226777&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9226/9226777_sc.jpg",
          "customerReviewCount": 576,
          "category": "USB Flash Drives",
          "objectID": 9226777,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra 8GB SDHC UHS-I Class 10 Memory Card",
          "shortDescription": "Compatible with most digital cameras and camcorders with a SDHC slot; 8GB capacity; up to 30MB/sec. read and write speeds; durable design",
          "bestSellingRank": 78,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5577/5577795_s.gif",
          "salePrice": 12.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-8gb-sdhc-uhs-i-class-10-memory-card/5577795.p?id=1218665493050&skuId=5577795&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5577/5577795_sc.jpg",
          "customerReviewCount": 1543,
          "category": "Secure Digital",
          "objectID": 5577795,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "HP - 564 3-Pack Cyan/Magenta/Yellow Original Ink Cartridges - Cyan/Magenta/Yellow",
          "shortDescription": "Compatible with select HP Photosmart printers; cyan, magenta and yellow ink; 20 sheets of photo paper",
          "bestSellingRank": 82,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6502/6502226_54x54_s.gif",
          "salePrice": 29.99,
          "manufacturer": "HP",
          "url": "http://www.bestbuy.com/site/hp-564-3-pack-cyan-magenta-yellow-original-ink-cartridges-cyan-magenta-yellow/6502226.p?id=1218752782021&skuId=6502226&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6502/6502226_105x105_sc.jpg",
          "customerReviewCount": 1582,
          "category": "Hewlett-Packard",
          "objectID": 6502226,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Asus - 15.6\" Laptop - Intel Celeron - 4GB Memory - 500GB Hard Drive - Black",
          "shortDescription": "Windows 8.1 64-bitTechnical details: Intel&#174; Celeron&#174; processor; 15.6\" display; 4GB memory; 500GB hard driveSpecial features: HDMI output",
          "bestSellingRank": 88,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/7288/7288011_s.gif",
          "salePrice": 249.99,
          "manufacturer": "Asus",
          "url": "http://www.bestbuy.com/site/asus-15-6-laptop-intel-celeron-4gb-memory-500gb-hard-drive-black/7288011.p?id=1219262036899&skuId=7288011&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/7288/7288011_sc.jpg",
          "customerReviewCount": 4,
          "category": "PC Laptops",
          "objectID": 7288011,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "Insignia™ - 4' Micro USB Cable - Black",
          "shortDescription": "Compatible with most micro USB-enabled devices; lets you charge and transfer data to compatible devices; sync capability; low-profile design; 4' length",
          "bestSellingRank": 94,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019341_s.gif",
          "salePrice": 14.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-4-micro-usb-cable-black/5019341.p?id=1219106277632&skuId=5019341&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5019/5019341_sc.jpg",
          "customerReviewCount": 92,
          "category": "Wall Chargers & Power Adapters",
          "objectID": 5019341,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Sony - PlayStation 4 (500GB)",
          "shortDescription": "Experience the evolution of gaming",
          "bestSellingRank": 95,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240103_s.gif",
          "salePrice": 399.99,
          "manufacturer": "Sony",
          "url": "http://www.bestbuy.com/site/sony-playstation-4-500gb/8240103.p?id=1218866963585&skuId=8240103&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240103_sc.jpg",
          "customerReviewCount": 7461,
          "category": "PS4 Consoles",
          "objectID": 8240103,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "Microsoft Office 365 Personal (1 Mac or PC + 1 Tablet) (1-Year Subscription) - Mac/Windows",
          "shortDescription": "Access amazing tools and features, no matter where you are",
          "bestSellingRank": 97,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5058/5058004_s.gif",
          "salePrice": 69.99,
          "manufacturer": "Microsoft",
          "url": "http://www.bestbuy.com/site/microsoft-office-365-personal-1-mac-or-pc-1-tablet-1-year-subscription-mac-windows/5058004.p?id=1219110267684&skuId=5058004&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Software",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5058/5058004_sc.jpg",
          "customerReviewCount": 91,
          "category": "Office Software Suites",
          "objectID": 5058004,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "2-Year Replacement Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 98,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif",
          "salePrice": 14.99,
          "url": "http://www.bestbuy.com/site/2-year-replacement-plan-geek-squad/9998166.p?id=1218318856136&skuId=9998166&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
          "customerReviewCount": null,
          "category": null,
          "objectID": 9998166,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Trend Micro Internet Security (3-Device) (1-Year Subscription) - Mac/Windows",
          "shortDescription": "Defend up to 3 devices against virtual intruders and online threats",
          "bestSellingRank": 101,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5147/5147463_s.gif",
          "salePrice": 49.99,
          "manufacturer": "Trend Micro",
          "url": "http://www.bestbuy.com/site/trend-micro-internet-security-3-device-1-year-subscription-mac-windows/5147463.p?id=1219112460836&skuId=5147463&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Software",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5147/5147463_sc.jpg",
          "customerReviewCount": 6,
          "category": "Computer Security Software",
          "objectID": 5147463,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Apple® - $15 iTunes Gift Card",
          "shortDescription": "Redeemable at the iTunes store, iBookstore or the App Store; redeemable for music, movies, eBooks, apps and more; $15 value",
          "bestSellingRank": 106,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695167_s.gif",
          "salePrice": 15.0,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-15-itunes-gift-card/3695167.p?id=1219093057698&skuId=3695167&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695167_sc.jpg",
          "customerReviewCount": null,
          "category": "iTunes Cards",
          "objectID": 3695167,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "WD - My Passport Ultra 1TB External USB 3.0 Hard Drive - Black",
          "shortDescription": "USB 3.0 interface; password protection; hardware encryption; data transfer rates up to 480 Mbps",
          "bestSellingRank": 109,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9028/9028431_s.gif",
          "salePrice": 69.99,
          "manufacturer": "WD",
          "url": "http://www.bestbuy.com/site/wd-my-passport-ultra-1tb-external-usb-3-0-hard-drive-black/9028431.p?id=1218971610403&skuId=9028431&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9028/9028431_sc.jpg",
          "customerReviewCount": 642,
          "category": "External Hard Drives",
          "objectID": 9028431,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Apple® - USB Power Adapter - White",
          "shortDescription": "Compatible with all iPhone&#174; and iPod models",
          "bestSellingRank": 114,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6653/6653042_54x54_s.gif",
          "salePrice": 18.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-usb-power-adapter-white/6653042.p?id=1218803449615&skuId=6653042&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6653/6653042_105x105_sc.jpg",
          "customerReviewCount": 78,
          "category": "Adapters",
          "objectID": 6653042,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Extreme PLUS 32GB microSDHC UHS-I Class U-1 Memory Card",
          "shortDescription": "Compatible with most devices with a microSDHC slot; includes SD/SDHC/SDXC adapter; 32GB capacity; Ultra High Speed (UHS-I) bus architecture",
          "bestSellingRank": 115,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9387/9387066_s.gif",
          "salePrice": 34.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-extreme-plus-32gb-microsdhc-uhs-i-class-u-1-memory-card/9387066.p?id=1219014148623&skuId=9387066&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9387/9387066_sc.jpg",
          "customerReviewCount": 271,
          "category": "Secure Digital",
          "objectID": 9387066,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "ZAGG - InvisibleSHIELD Glass Screen Protector for Apple® iPhone® 5, 5s and 5c",
          "shortDescription": "Compatible with Apple iPhone 5, 5s and 5c; tempered-glass material; smooth touch; tapered edges; easy-to-install design",
          "bestSellingRank": 117,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3699/3699012_s.gif",
          "salePrice": 39.99,
          "manufacturer": "ZAGG",
          "url": "http://www.bestbuy.com/site/zagg-invisibleshield-glass-screen-protector-for-apple-iphone-5-5s-and-5c/3699012.p?id=1219093056982&skuId=3699012&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3699/3699012_sc.jpg",
          "customerReviewCount": 215,
          "category": "Screen Protectors",
          "objectID": 3699012,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Rocketfish™ - 4' In-Wall HDMI Cable",
          "shortDescription": "Connects an HDMI component to an HDTV or projector with an HDMI input; 3-layer cable shielding; 360&#176; metal connector shell; silver content soldering; 24K gold-plated contacts",
          "bestSellingRank": 118,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3720/3720002_s.gif",
          "salePrice": 29.99,
          "manufacturer": "Rocketfish™",
          "url": "http://www.bestbuy.com/site/rocketfish-4-in-wall-hdmi-cable/3720002.p?id=1219093273029&skuId=3720002&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3720/3720002_sc.jpg",
          "customerReviewCount": 61,
          "category": "HDMI Cables",
          "objectID": 3720002,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Extreme PLUS 32GB SDHC UHS-I Memory Card",
          "shortDescription": "Compatible with most digital cameras and camcorders with a SDHC slot; 32GB capacity; up to 80MB/sec. read speeds and up to 60MB/sec. write speeds",
          "bestSellingRank": 122,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3990/3990822_s.gif",
          "salePrice": 34.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-extreme-plus-32gb-sdhc-uhs-i-memory-card/3990822.p?id=1218444831583&skuId=3990822&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3990/3990822_sc.jpg",
          "customerReviewCount": 462,
          "category": "Secure Digital",
          "objectID": 3990822,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "HP - 564 Black Vivera Original Ink Cartridge - Black",
          "shortDescription": "Compatible with HP d5460, ps pro68550, psc6380 and psc6760 printers; dries instantly and resists smudges; dark black",
          "bestSellingRank": 124,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8891/8891853_54x108_s.gif",
          "salePrice": 12.99,
          "manufacturer": "HP",
          "url": "http://www.bestbuy.com/site/hp-564-black-vivera-original-ink-cartridge-black/8891853.p?id=1211587727159&skuId=8891853&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/8891/8891853_105x210_sc.jpg",
          "customerReviewCount": 1404,
          "category": "Printer Ink",
          "objectID": 8891853,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "RCA - Indoor HDTV Antenna - White",
          "shortDescription": "Receives local HD and digital TV broadcasts; supports VHF and UHF frequencies; flat design",
          "bestSellingRank": 125,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8939/8939839_r.gif",
          "salePrice": 18.99,
          "manufacturer": "RCA",
          "url": "http://www.bestbuy.com/site/rca-indoor-hdtv-antenna-white/8939839.p?id=1215217075905&skuId=8939839&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/8939/8939839_rc.jpg",
          "customerReviewCount": 1345,
          "category": "TV Antennas",
          "objectID": 8939839,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Apple® - $25 iTunes Gift Card",
          "shortDescription": "Redeemable at the iTunes Store, iBookstore or the App Store; redeemable for music, movies, eBooks, apps and more; $25 value",
          "bestSellingRank": 128,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695176_s.gif",
          "salePrice": 25.0,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-25-itunes-gift-card/3695176.p?id=1219093055202&skuId=3695176&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3695/3695176_sc.jpg",
          "customerReviewCount": null,
          "category": "iTunes Cards",
          "objectID": 3695176,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "HP - Pavilion 17.3\" Laptop - AMD A8 - 4GB Memory - 750GB Hard Drive - Anodized Silver",
          "shortDescription": "Windows 8.1 64-bitTechnical details: AMD A8-Series processor; 17.3\" display; 4GB memory; 750GB hard driveSpecial features: HDMI output",
          "bestSellingRank": 129,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5862/5862002_s.gif",
          "salePrice": 379.99,
          "manufacturer": "HP",
          "url": "http://www.bestbuy.com/site/hp-pavilion-17-3-laptop-amd-a8-4gb-memory-750gb-hard-drive-anodized-silver/5862002.p?id=1219165145852&skuId=5862002&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5862/5862002_sc.jpg",
          "customerReviewCount": 18,
          "category": "PC Laptops",
          "objectID": 5862002,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "Apple® - MacBook Air® (Latest Model) - 13.3\" Display - Intel Core i5 - 4GB Memory - 128GB Flash Storage",
          "shortDescription": "4th Gen Intel&#174; Core&#8482; i5 processor; 13.3\" display; 4GB memory; 128GB flash storageSpecial features: Bluetooth 4.0Note: DVD/CD drive not included",
          "bestSellingRank": 130,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/2712/2712009_s.gif",
          "salePrice": 949.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-macbook-air-latest-model-13-3-display-intel-core-i5-4gb-memory-128gb-flash-storage/2712009.p?id=1219076158205&skuId=2712009&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/2712/2712009_sc.jpg",
          "customerReviewCount": 123,
          "category": "MacBooks",
          "objectID": 2712009,
          "shipping": "Free shipping",
          "salePrice_range": "501 - 2000"
        },
        {
          "name": "Apple - USB Cable Adapter",
          "shortDescription": "USB - Proprietary Connector",
          "bestSellingRank": 131,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1551/1551069_s.gif",
          "salePrice": 18.99,
          "manufacturer": "Apple",
          "url": "http://www.bestbuy.com/site/apple-usb-cable-adapter/1551069.p?id=1218268438450&skuId=1551069&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1551/1551069_sc.jpg",
          "customerReviewCount": 133,
          "category": "iPod & MP3 Cables & Connectors",
          "objectID": 1551069,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "2-Year Replacement Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 132,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif",
          "salePrice": 19.99,
          "url": "http://www.bestbuy.com/site/2-year-replacement-plan-geek-squad/9998236.p?id=1218318854985&skuId=9998236&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
          "customerReviewCount": null,
          "category": null,
          "objectID": 9998236,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "SanDisk - Ultra Plus 64GB microSDXC Class 10 UHS-1 Memory Card",
          "shortDescription": "Compatible with most devices with a microSDXC slot; 64GB capacity; temperature-, X-ray-, shock- and waterproof design; writeable label",
          "bestSellingRank": 133,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142644_s.gif",
          "salePrice": 49.99,
          "manufacturer": "SanDisk",
          "url": "http://www.bestbuy.com/site/sandisk-ultra-plus-64gb-microsdxc-class-10-uhs-1-memory-card/3142644.p?id=1219088216907&skuId=3142644&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3142/3142644_sc.jpg",
          "customerReviewCount": 132,
          "category": "Micro SD Memory",
          "objectID": 3142644,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Fitbit - Flex Wireless Activity and Sleep Tracker Wristband - Black",
          "shortDescription": "Measures steps, distance, calories burned and active minutes; monitors sleep cycle; silent alarm; LED lights; water-resistant design; rechargeable battery",
          "bestSellingRank": 135,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8390/8390054_s.gif",
          "salePrice": 99.99,
          "manufacturer": "Fitbit",
          "url": "http://www.bestbuy.com/site/fitbit-flex-wireless-activity-and-sleep-tracker-wristband-black/8390054.p?id=1218874428772&skuId=8390054&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/8390/8390054_sc.jpg",
          "customerReviewCount": 2901,
          "category": "Activity Trackers & Pedometers",
          "objectID": 8390054,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Redeemer of Souls [Deluxe Edition] - CD",
          "shortDescription": null,
          "bestSellingRank": 139,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/6523/6523078s.jpg",
          "salePrice": 17.99,
          "manufacturer": "Epic (USA)",
          "url": "http://www.bestbuy.com/site/redeemer-of-souls-deluxe-edition-cd/6523078.p?id=3239850&skuId=6523078&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "Music",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/6523/6523078.jpg",
          "customerReviewCount": null,
          "category": "Hard Rock",
          "objectID": 6523078,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Sony - DualShock 4 Wireless Controller for PlayStation 4",
          "shortDescription": "Experience the evolution of controllers",
          "bestSellingRank": 140,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240079_s.gif",
          "salePrice": 59.99,
          "manufacturer": "Sony",
          "url": "http://www.bestbuy.com/site/sony-dualshock-4-wireless-controller-for-playstation-4/8240079.p?id=1218866963583&skuId=8240079&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/8240/8240079_sc.jpg",
          "customerReviewCount": 1007,
          "category": "PS4 Controllers",
          "objectID": 8240079,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Insignia™ - Micro USB Wall Charger",
          "shortDescription": "Compatible with most micro USB-enabled devices; 12W of power; 2.4-amp output; folding blades; power-indicator LED; includes 4' micro USB charge-and-sync cable",
          "bestSellingRank": 142,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5689/5689149_s.gif",
          "salePrice": 19.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-micro-usb-wall-charger/5689149.p?id=1219148349638&skuId=5689149&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5689/5689149_sc.jpg",
          "customerReviewCount": null,
          "category": "Adapters, Cables & Chargers",
          "objectID": 5689149,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "LG - Tone Pro Bluetooth Headset",
          "shortDescription": "Compatible with most Bluetooth 3.0-enabled cell phones; 3D NeckBehind design; HD Voice and aptX technologies; echo cancellation; noise reduction; Google Voice Actions integration; in-line controls",
          "bestSellingRank": 145,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/4950/4950032_s.gif",
          "salePrice": 69.99,
          "manufacturer": "LG",
          "url": "http://www.bestbuy.com/site/lg-tone-pro-bluetooth-headset/4950032.p?id=1219105377462&skuId=4950032&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/4950/4950032_sc.jpg",
          "customerReviewCount": 222,
          "category": "Headphones",
          "objectID": 4950032,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "NETGEAR - RangeMax Dual-Band Wireless-N Router with 4 Ethernet Ports",
          "shortDescription": "ENERGY STAR Certified\nUp to 600 Mbps data transfer rates; Push'N'Connect setup; broadband usage meter",
          "bestSellingRank": 146,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/1208/1208844_x_r.gif",
          "salePrice": 74.99,
          "manufacturer": "NETGEAR",
          "url": "http://www.bestbuy.com/site/netgear-rangemax-dual-band-wireless-n-router-with-4-ethernet-ports/1208844.p?id=1218234872989&skuId=1208844&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/1208/1208844_105x105_sc.jpg",
          "customerReviewCount": 4048,
          "category": "Routers",
          "objectID": 1208844,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "2-Year Replacement Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 148,
          "thumbnailImage": null,
          "salePrice": 14.99,
          "url": "http://www.bestbuy.com/site/2-year-replacement-plan-geek-squad/9996583.p?id=1218318237605&skuId=9996583&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": null,
          "customerReviewCount": null,
          "category": null,
          "objectID": 9996583,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "2-Year Replacement Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 149,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif",
          "salePrice": 8.99,
          "url": "http://www.bestbuy.com/site/2-year-replacement-plan-geek-squad/9998096.p?id=1218318851846&skuId=9998096&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
          "customerReviewCount": null,
          "category": null,
          "objectID": 9998096,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Frigidaire - Semi-Rigid Dryer Vent Kit Required for Hook-Up - Silver",
          "shortDescription": "Expandable vent; custom fitted ends and clamps",
          "bestSellingRank": 150,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/9282/9282812_s.gif",
          "salePrice": 26.99,
          "manufacturer": "Frigidaire",
          "url": "http://www.bestbuy.com/site/frigidaire-semi-rigid-dryer-vent-kit-required-for-hook-up-silver/9282812.p?id=1218073823670&skuId=9282812&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/9282/9282812_sc.jpg",
          "customerReviewCount": 797,
          "category": "Dryer Accessories",
          "objectID": 9282812,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Insignia™ - 19\" Class (18-1/2\" Diag.) - LED - 720p - 60Hz - HDTV",
          "shortDescription": "ENERGY STAR Certified",
          "bestSellingRank": 153,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/2799/2799043_s.gif",
          "salePrice": 89.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-19-class-18-1-2-diag--led-720p-60hz-hdtv/2799043.p?id=1219077483779&skuId=2799043&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/2799/2799043_sc.jpg",
          "customerReviewCount": 72,
          "category": "Flat-Panel TVs",
          "objectID": 2799043,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Insignia™ - AC Laptop Power Adapter",
          "shortDescription": "Compatible with select laptops that require 90W of power or less; 19V output; thermal, over-current and short-circuit protection",
          "bestSellingRank": 156,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/5202/5202025_s.gif",
          "salePrice": 54.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-ac-laptop-power-adapter/5202025.p?id=1219114901041&skuId=5202025&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/5202/5202025_sc.jpg",
          "customerReviewCount": null,
          "category": "Cables, Chargers & Adapters",
          "objectID": 5202025,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        },
        {
          "name": "Insignia™ - 32\" Class (31-1/2\" Diag.) - LED - 720p - 60Hz - HDTV",
          "shortDescription": "ENERGY STAR Certified",
          "bestSellingRank": 157,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/3356/3356036_s.gif",
          "salePrice": 179.99,
          "manufacturer": "Insignia™",
          "url": "http://www.bestbuy.com/site/insignia-32-class-31-1-2-diag--led-720p-60hz-hdtv/3356036.p?id=1219091131759&skuId=3356036&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/3356/3356036_sc.jpg",
          "customerReviewCount": 218,
          "category": "Flat-Panel TVs",
          "objectID": 3356036,
          "shipping": "Free shipping",
          "salePrice_range": "201 - 500"
        },
        {
          "name": "2-Year Replacement Plan - Geek Squad",
          "shortDescription": "",
          "bestSellingRank": 159,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_s.gif",
          "salePrice": 29.99,
          "url": "http://www.bestbuy.com/site/2-year-replacement-plan-geek-squad/9998272.p?id=1218318854446&skuId=9998272&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "BlackTie",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/nonsku/default_hardlines_l.jpg",
          "customerReviewCount": null,
          "category": null,
          "objectID": 9998272,
          "shipping": "Free shipping",
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Samsung - Galaxy S 5 4G LTE Cell Phone - Charcoal Black (Verizon Wireless)",
          "shortDescription": "Qualcomm Snapdragon 801 MSM 8974AC 2.5GHz quad-core processorAndroid 4.4.2 KitKat operating system4G LTE speedWi-Fi5.1\" Super AMOLED touch screen",
          "bestSellingRank": 160,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/4811/4811019_s.gif",
          "salePrice": 749.99,
          "manufacturer": "Samsung",
          "url": "http://www.bestbuy.com/site/samsung-galaxy-s-5-4g-lte-cell-phone-charcoal-black-verizon-wireless/4811019.p?id=1219103774662&skuId=4811019&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/4811/4811019_sc.jpg",
          "customerReviewCount": 464,
          "category": "Cell Phones with Plans",
          "objectID": 4811019,
          "shipping": "Free shipping",
          "salePrice_range": "501 - 2000"
        },
        {
          "name": "Apple® - 6.6' Lightning-to-USB 2.0 Cable",
          "shortDescription": "Compatible with most Apple&#174; iPad&#174;, iPhone&#174; and iPod&#174; models with a Lightning connector; charges and syncs your device; reversible design",
          "bestSellingRank": 161,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/2253/2253772_s.gif",
          "salePrice": 29.99,
          "manufacturer": "Apple®",
          "url": "http://www.bestbuy.com/site/apple-6-6-lightning-to-usb-2-0-cable/2253772.p?id=1219070443474&skuId=2253772&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/2253/2253772_sc.jpg",
          "customerReviewCount": 103,
          "category": "Data Cables",
          "objectID": 2253772,
          "shipping": null,
          "salePrice_range": "1 - 50"
        },
        {
          "name": "Garmin - nüvi 42LM Essential Series 4.3\" GPS with Lifetime Map Updates",
          "shortDescription": "Preloaded base map coverage of the lower 48 U.S. states, Hawaii, Puerto Rico, U.S. Virgin Islands, Cayman Islands and Bahamas; 4.3\" touch-screen display; text-to-speech technology",
          "bestSellingRank": 162,
          "thumbnailImage": "http://img.bbystatic.com/BestBuy_US/images/products/7534/7534182_54x108_s.gif",
          "salePrice": 89.99,
          "manufacturer": "Garmin",
          "url": "http://www.bestbuy.com/site/garmin-nvi-42lm-essential-series-4-3-gps-with-lifetime-map-updates/7534182.p?id=1218849840607&skuId=7534182&cmp=RMX&ky=2d3GfEmNIzjA0vkzveHdZEBgpPCyMnLTJ",
          "type": "HardGood",
          "image": "http://img.bbystatic.com/BestBuy_US/images/products/7534/7534182_105x210_sc.jpg",
          "customerReviewCount": 269,
          "category": "Portable GPS",
          "objectID": 7534182,
          "shipping": "Free shipping",
          "salePrice_range": "101 - 200"
        }
      ]
    json
    )
  end
end

